FROM node:22-alpine

WORKDIR /app

COPY package* .
RUN npm ci

# copying src/, public/, and tsconfig.json
COPY . .
CMD ["npm", "start"]

# docker run --rm -d -p 3000:3000 -v ./public:/app -v ./src:/app react-app:dev
